name: Build and Deploy Product API

on:
  push:
    branches:
      - feature/azure-deployment

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore Product API
        run: dotnet restore ProductApi/ProductApi.csproj

      - name: Build Product API
        run: dotnet build ProductApi/ProductApi.csproj --configuration Release --no-restore

      - name: Restore tests
        run: dotnet restore ProductApi.Tests/ProductApi.Tests.csproj

      - name: Build tests
        run: dotnet build ProductApi.Tests/ProductApi.Tests.csproj --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test ProductApi.Tests/ProductApi.Tests.csproj --configuration Release --no-build

      - name: Publish Product API
        run: dotnet publish ProductApi/ProductApi.csproj --configuration Release --output ./publish

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: product-api
          path: ./publish

  deploy:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: product-api

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'jayashree-product-api-2026'
          slot-name: 'Production'
          package: .