name: .NET CI

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore ProductApi/ProductApi.csproj

      - name: Build
        run: dotnet build ProductApi/ProductApi.csproj --no-restore

      - name: Test
        run: dotnet test ProductApi/ProductApi.csproj --no-build

      - name: Restore dependencies
        run: dotnet restore ProductApi.Tests/ProductApi.Tests.csproj

      - name: Build
        run: dotnet build ProductApi.Tests/ProductApi.Tests.csproj --no-restore

      - name: Test
        run: dotnet test ProductApi.Tests/ProductApi.Tests.csproj --no-build