# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - jayashree-product-api-2026

on:
  push:
    branches:
      - feature/azure-deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build Product API
        run: dotnet build ProductApi/ProductApi.csproj --configuration Release
      
      - name: Restore tests
        run: dotnet restore ProductApi.Tests/ProductApi.Tests.csproj

      - name: Build tests
        run: dotnet build ProductApi.Tests/ProductApi.Tests.csproj --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test ProductApi.Tests/ProductApi.Tests.csproj --configuration Release --no-build

      - name: Publish Product API
        run: dotnet publish ProductApi/ProductApi.csproj --configuration Release --output ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7A5612671F7547C291F8565B2208AD1F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_922802AA727E46E991A03F78B620B92F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0FFD9D532AA5455F9FE7B1B92C8EBA80 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'jayashree-product-api-2026'
          slot-name: 'Production'
          package: .
          